import { Link, Button, Divider } from '@nextui-org/react'
import Image from 'next/image'
import { FaStar } from "react-icons/fa";
import { GetStaticPaths, GetStaticProps } from 'next';
import { useRouter } from 'next/navigation';

export default function AskAQuestion() {
  return (
    <main className='flex flex-col justify-around items-center'>
        <h1 className='font-bold text-7xl text-white text-center'>IGCSE: Chemistry - Edexcel: Ionic Bonding</h1>
        <div className='flex flex-row justify-around items-center max-w-[1200px] lg:w-[1200px] my-60 gap-10 p-10 bg-white rounded-lg border-8 border-amber-300'>
            <h1 className='font-bold text-3xl text-black text-center'>AI Features</h1>
            <div className='grid grid-cols-4 gap-5'>
                <Button as={Link} href="/curriculum/igcse/chemistry-edexcel/ionic-bonding/revision-notes" className='bg-[#f4ebe3] text-black text-xl font-semibold px-4'>Revision Notes</Button>
                <Button as={Link} href="/curriculum/igcse/chemistry-edexcel/ionic-bonding/summary" className='bg-[#f4ebe3] text-black text-xl font-semibold px-4'>Summary Generator</Button>
                <Button as={Link} href="/curriculum/igcse/chemistry-edexcel/ionic-bonding/flashcards" className='bg-[#f4ebe3] text-black text-xl font-semibold px-4'>Flashcards</Button>
                <Button as={Link} href="/curriculum/igcse/chemistry-edexcel/ionic-bonding/ask-a-question" className='bg-[#f4ebe3] text-black text-xl font-semibold px-4'>Ask a Question</Button>
            </div>
        </div>
        <div className='flex flex-row justify-around items-center max-w-[1200px] lg:w-[1200px] my-60 gap-10 p-10 bg-white rounded-lg border-8 border-pink-400'>
            <div className='grid grid-cols-1 gap-5'>
                <h1 className='font-bold text-3xl text-black text-center'>Ask A Question</h1>
                <hr></hr>
                <p className='text-black'>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo urna molestie at elementum. Eu mi bibendum neque egestas. Porttitor eget dolor morbi non arcu risus quis varius. Auctor eu augue ut lectus arcu bibendum. Tincidunt id aliquet risus feugiat in ante metus dictum. Sagittis eu volutpat odio facilisis mauris sit amet. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Commodo odio aenean sed adipiscing diam donec. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Enim sed faucibus turpis in eu. Elementum curabitur vitae nunc sed. Erat velit scelerisque in dictum non consectetur a. <br></br><br></br>

                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Nunc congue nisi vitae suscipit tellus mauris. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Ornare massa eget egestas purus viverra accumsan. Malesuada proin libero nunc consequat interdum varius sit amet. Ullamcorper malesuada proin libero nunc consequat. Amet risus nullam eget felis eget nunc. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Ultricies leo integer malesuada nunc vel risus commodo viverra. Enim nunc faucibus a pellentesque sit amet porttitor eget. Elit sed vulputate mi sit. Fermentum iaculis eu non diam phasellus vestibulum lorem. Elementum tempus egestas sed sed risus. Est sit amet facilisis magna etiam tempor orci. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Eget mi proin sed libero enim. Ut eu sem integer vitae. <br></br><br></br>

                    Sit amet aliquam id diam maecenas ultricies. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Sit amet risus nullam eget felis eget. Lectus proin nibh nisl condimentum id venenatis a. Nascetur ridiculus mus mauris vitae. Tristique senectus et netus et malesuada fames ac. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Aliquam ultrices sagittis orci a. Risus sed vulputate odio ut enim blandit. Leo vel orci porta non pulvinar. Enim tortor at auctor urna nunc id. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Consectetur adipiscing elit pellentesque habitant morbi. Bibendum neque egestas congue quisque. <br></br><br></br>

                    Morbi tincidunt augue interdum velit euismod. Quis vel eros donec ac. Vivamus at augue eget arcu dictum varius duis. Risus in hendrerit gravida rutrum quisque. Placerat vestibulum lectus mauris ultrices eros in cursus. Eu tincidunt tortor aliquam nulla facilisi cras. Aliquet nec ullamcorper sit amet risus nullam eget felis. Et malesuada fames ac turpis egestas sed. Nec ullamcorper sit amet risus nullam. Vivamus arcu felis bibendum ut tristique et egestas quis. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Ac tortor dignissim convallis aenean et tortor. Dignissim diam quis enim lobortis scelerisque fermentum. Massa enim nec dui nunc mattis enim ut tellus elementum. At erat pellentesque adipiscing commodo elit at imperdiet dui. <br></br><br></br>

                    Sed enim ut sem viverra aliquet eget sit amet. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Suscipit tellus mauris a diam maecenas sed enim ut. Congue nisi vitae suscipit tellus mauris a. Odio eu feugiat pretium nibh ipsum consequat nisl. Urna nunc id cursus metus aliquam eleifend mi. Arcu ac tortor dignissim convallis aenean et tortor at. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Amet mattis vulputate enim nulla aliquet porttitor. Sagittis orci a scelerisque purus semper eget duis at tellus. In eu mi bibendum neque. Adipiscing enim eu turpis egestas pretium. <br></br><br></br>

                    Cras tincidunt lobortis feugiat vivamus at augue eget. Quisque egestas diam in arcu cursus euismod quis viverra. Nunc faucibus a pellentesque sit amet. Velit aliquet sagittis id consectetur purus ut faucibus. Ut morbi tincidunt augue interdum velit. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Suspendisse faucibus interdum posuere lorem ipsum. Nibh sit amet commodo nulla facilisi nullam. Consequat mauris nunc congue nisi. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. <br></br><br></br>

                    Sem et tortor consequat id. Auctor urna nunc id cursus metus aliquam eleifend mi in. Vitae justo eget magna fermentum. Non quam lacus suspendisse faucibus interdum posuere lorem. Consectetur purus ut faucibus pulvinar elementum. Vivamus at augue eget arcu dictum varius duis at consectetur. Gravida rutrum quisque non tellus orci ac auctor. Purus in mollis nunc sed id semper risus in. Sed tempus urna et pharetra pharetra. Diam in arcu cursus euismod quis viverra nibh cras. Tempor orci dapibus ultrices in iaculis nunc sed augue. Ipsum dolor sit amet consectetur adipiscing. Aenean pharetra magna ac placerat vestibulum lectus mauris. Suscipit tellus mauris a diam maecenas sed enim ut sem. Pharetra convallis posuere morbi leo urna molestie at elementum eu. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Diam ut venenatis tellus in metus vulputate eu scelerisque. Vitae proin sagittis nisl rhoncus. <br></br><br></br>

                    Non enim praesent elementum facilisis leo vel fringilla. Mauris augue neque gravida in fermentum et sollicitudin ac orci. Nulla posuere sollicitudin aliquam ultrices. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Ac feugiat sed lectus vestibulum mattis. Amet commodo nulla facilisi nullam vehicula ipsum a. Dui vivamus arcu felis bibendum ut. Pretium viverra suspendisse potenti nullam ac. Nec ultrices dui sapien eget mi proin. Tellus orci ac auctor augue mauris. Amet mauris commodo quis imperdiet massa. Justo donec enim diam vulputate ut pharetra sit amet aliquam. <br></br><br></br>

                    Eu augue ut lectus arcu bibendum. Nibh nisl condimentum id venenatis a condimentum. Purus sit amet volutpat consequat mauris nunc congue nisi. Facilisis volutpat est velit egestas dui. Non nisi est sit amet facilisis magna. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Sem et tortor consequat id porta nibh venenatis cras. Quis imperdiet massa tincidunt nunc. Dictum non consectetur a erat. Erat nam at lectus urna duis convallis convallis. Enim ut sem viverra aliquet eget sit amet tellus cras. Nisl tincidunt eget nullam non nisi est sit amet facilisis. <br></br><br></br>

                    Lorem donec massa sapien faucibus et molestie ac feugiat. Euismod lacinia at quis risus sed vulputate. Ultrices in iaculis nunc sed augue lacus. Interdum consectetur libero id faucibus. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. In massa tempor nec feugiat nisl pretium. Aliquam etiam erat velit scelerisque in dictum. Sit amet nisl purus in mollis nunc sed id. Nisi scelerisque eu ultrices vitae auctor eu. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Ultrices eros in cursus turpis massa. <br></br><br></br>
                </p>
            </div>
        </div>
    </main>)}